'use strict';

var index = require('./index-831d13b2.js');

/* src/pages/About.svelte generated by Svelte v3.44.0 */

const About = index.create_ssr_component(($$result, $$props, $$bindings, slots) => {
	return `<h1 class="${"text-6xl"}">About me</h1>
<a href="${"/views/app"}">Home</a>`;
});

module.exports = About;
