'use strict';

var index = require('./index-831d13b2.js');

/* src/pages/App.svelte generated by Svelte v3.44.0 */

const App = index.create_ssr_component(($$result, $$props, $$bindings, slots) => {
	let { name } = $$props;
	let count = 0;
	if ($$props.name === void 0 && $$bindings.name && name !== void 0) $$bindings.name(name);

	return `<main class="${"p-12"}"><h1 class="${"text-red-500 font-bold text-4xl"}">Hello ${index.escape(name)}!</h1>
	<p class="${"text-lg text-gray-700"}">Visit the <a href="${"https://svelte.dev/tutorial"}">Svelte tutorial</a> to learn how to build Svelte apps.</p>
	<a href="${"/views/about"}" class="${"underline text-blue-500"}">About me</a>

	<p>${index.escape(count)}</p>
	<button class="${"bg-emerald-200 px-5 py-3 rounded-lg"}">Increment</button>
	<button>Decrement</button>
</main>`;
});

module.exports = App;
